export SECURITY_MODE=cookie
echo 'KRATOS_BROWSER_URL='$KRATOS_BROWSER_URL
echo 'KRATOS_PUBLIC_URL='$KRATOS_PUBLIC_URL
echo 'KRATOS_ADMIN_URL='$KRATOS_ADMIN_URL
echo 'BASE_URL='$BASE_URL
echo 'PORT='$PORT

# npm run serve
npm start
